add_rules("mode.debug", "mode.release")
add_requires("folly 2024.04.01", {configs = {cxxstd = "c++20"}})
add_requires("fmt")
add_requires("gtest")
add_requires("benchmark")
add_requires("rapidjson")
add_requires("libunwind")

set_languages("c++20")

target("demolib")
    set_kind("static")
    add_files("src/demolib/*.cpp")

target("xmake-test")
    set_kind("binary")
    add_files("src/*.cpp")
    add_includedirs("src/demolib")
    add_defines("FOLLY_HAS_COROUTINES")
    add_deps("demolib")
    add_packages("folly")
    add_packages("fmt")
    add_packages("libunwind")

target("gtest-test")
    add_deps("demolib")
    set_kind("binary")
    add_files("tests/*.cpp")
    add_includedirs("src/demolib")
    add_defines("FOLLY_HAS_COROUTINES")
    add_packages("folly")
    add_packages("fmt")
    add_packages("gtest")


target("benchmark-test")
    add_deps("demolib")
    set_kind("binary")
    add_files("benchmark/*.cpp")
    add_includedirs("src/demolib")
    add_defines("FOLLY_HAS_COROUTINES")
    add_packages("folly")
    add_packages("fmt")
    add_packages("rapidjson")
    add_packages("benchmark")

